### ISSUE TITLE
crashed on executing CLI "ca importprofiles" when certificatepolicies present in input xml

### ISSUE THREAD

**Issue by cbxia** [primekeydevs/ejbca-ce#6]
Hello, I tried to import a certificate profile that was exported from another ejbca instance, which contains a certificatepolicies definition. I got the following error: 

================[error message]=================
2021-06-07 14:15:12,880+0000 INFO  [org.ejbca.ui.cli.ca.CaImportProfilesCommand] (main) Importing certificate and end entity profiles:
2021-06-07 14:15:12,928+0000 INFO  [org.ejbca.ui.cli.ca.CaImportProfilesCommand] (main) Filename: 'certprofile_PMRootCA-1312821369.xml'
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/reflect/MethodUtils
        at org.cesecore.util.SecureXMLDecoder.parseObject(SecureXMLDecoder.java:820)
        at org.cesecore.util.SecureXMLDecoder.readValue(SecureXMLDecoder.java:335)
        at org.cesecore.util.SecureXMLDecoder.readValue(SecureXMLDecoder.java:187)
        at org.cesecore.util.SecureXMLDecoder.parseCollection(SecureXMLDecoder.java:659)
        at org.cesecore.util.SecureXMLDecoder.readValue(SecureXMLDecoder.java:296)
        at org.cesecore.util.SecureXMLDecoder.readValue(SecureXMLDecoder.java:187)
        at org.cesecore.util.SecureXMLDecoder.parseMap(SecureXMLDecoder.java:686)
        at org.cesecore.util.SecureXMLDecoder.readValue(SecureXMLDecoder.java:315)
        at org.cesecore.util.SecureXMLDecoder.readValue(SecureXMLDecoder.java:187)
        at org.cesecore.util.SecureXMLDecoder.readObject(SecureXMLDecoder.java:145)
        at org.ejbca.ui.cli.ca.CaImportProfilesCommand.execute(CaImportProfilesCommand.java:151)
        at org.ejbca.ui.cli.infrastructure.command.PasswordUsingCommandBase.execute(PasswordUsingCommandBase.java:201)
        at org.ejbca.ui.cli.infrastructure.library.CommandLibrary$Branch.execute(CommandLibrary.java:291)
        at org.ejbca.ui.cli.infrastructure.library.CommandLibrary$Branch.execute(CommandLibrary.java:302)
        at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.findAndExecuteCommandFromParameters(CommandLibrary.java:78)
        at org.ejbca.ui.cli.EjbcaEjbCli.main(EjbcaEjbCli.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.reflect.MethodUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 16 more

=============  [extract of profile definition xml] ===================\
`.... 
  <void method="put">
   <string>certificatepoliciescritical</string>
   <boolean>false</boolean>
  </void>
  <void method="put">
   <string>certificatepolicies</string>
   <object class="java.util.ArrayList">
    <void method="add">
     <object class="org.cesecore.certificates.certificateprofile.CertificatePolicy">
      <void property="policyID">
       <string>2.5.29.32.0</string>
      </void>
      <void property="qualifier">
       <string></string>
      </void>
      <void property="qualifierId">
       <string></string>
      </void>
     </object>
    </void>
   </object>
  </void>
....
`

**Comment by primetomas** [comment]
Hi, this is a known issue, and was fixed here:
https://jira.primekey.se/browse/ECA-9977

It will be available in the next release, and source update here in GitHub.

**Comment by cbxia** [comment]
Thank you enormously for your responsiveness. I should have checked beforehand the known issues...
Best regards,
Chengbin XIA

**Comment by primetomas** [comment]
No problem, it's not easy to find among all issues.
